spring:
  h2.console:
    enabled: true
    path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: kimej
    password: kimej1!

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
      hibernate.format_sql: true

logging:
  pattern:
    file: '[%d{yyyy-MM-dd HH:mm:ss}]-[%-5level]-[%logger.%method]-[%msg]%n'
  file:
    name: ./logs/project_.log
  level:
    root: info
    com.dauo.project: debug
  logback:
    rollingpolicy:
      file-name-pattern: './logs/project_%d{yyyy-MM-dd}-%i.log'

application:
  jwt-key: ejkim
  allow-ips:
    - 0:0:0:0:0:0:0:1
    - 192.168.1.1